version: '2.1'
services:
 
  letsencrypt:
    image: cybergatelabs/letsencrypt
    container_name: letsencrypt
    hostname: letsencrypt
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - URL=${URL}
      - SUBDOMAINS=${SUBDOMAINS},
      - EXTRA_DOMAINS=${EXTRA_DOMAINS}
      - VALIDATION=${VALIDATION}
      - EMAIL=${EMAIL}
      - DHLEVEL=${DHLEVEL}
      - ONLY_SUBDOMAINS=${ONLY_SUBDOMAINS}
      - STAGING=${STAGING}
      
    networks:
      cybererp-network:
        aliases:
          - letsencrypt
    volumes:
     - ./letsencrypt/config:/config 
    ports:
      - 443:443
      - 80:80 #optional
    restart: always
  
  pgadmin:
    image: adminer
    container_name: pgadmin
    hostname: pgadmin
    restart: always
    #ports:
    #  - 8080:8080
    # depends_on:
    #  - postgresql
    networks:
      cybererp-network:
        aliases:
          - pgadmin
 
  portainer:
    image: portainer/portainer
    container_name: portainer
    hostname: portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./conf/portainer:/data
    restart: always
    networks:
      cybererp-network:
        aliases:
         - portainer
  
  duplicati:
    image: linuxserver/duplicati
    container_name: duplicati
    hostname: duplicati
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - CLI_ARGS= #optional
    volumes:
      - ./config/dupicati:/config
      - /opt/backup/duplicati:/backups
      - ./:/source
    ports:
      - 8200:8200
    restart: always
    networks:
      cybererp-network:
        aliases:
         - duplicati
volumes:
  postgresql_data:
    driver: local
  odoo_data: 
    driver: local
networks:
  cybererp-network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-cybererp
    enable_ipv6: false
    ipam:
      driver: default
      config:
        - subnet: 172.26.1.0/24
        
