version: '2.1'
services:

  postgresql_CUSTOMER:
    image: 'bitnami/postgresql:11'
    container_name: postgresql_CUSTOMER
    hostname: postgresql
    volumes:
      - './postgresql_CUSTOMER_data:/bitnami/postgresql'
    networks:
      cybererp-CUSTOMER-net:
    env_file:
      - ./.env_CUSTOMER
    restart: always
    
  odoo_CUSTOMER:
    image: 'bitnami/odoo:12'
    container_name: odoo_CUSTOMER
    hostname: odoo
    volumes:  
      - './odoo_data/CUSTOMER:/bitnami'
      - './custom-addons/CUSTOMER/:/bitnami/odoo/addons/'
      - './custom-addons/CUSTOMER-uploads/:/bitnami/odoo/addons-uploads'
    env_file:
      - ./.env_CUSTOMER
    networks:
      cybererp-CUSTOMER-net:
    depends_on:
      - 3
    restart: always  
